[moisture]
; Soil moisture calibration constants determined empirically
; To get this values run the component moisture_calibration
; Min value corresponds to maximum water saturation (100% wet)
; Max value corresponds to open air exposure (0% dry)
build_flags = 
    -D MOISTURE_ADC_MIN_WET=600
    -D MOISTURE_ADC_MAX_DRY=2800

[network]
build_flags =
    -D WIFI_SSID=\"YOUR_WIFI_SSID\"
    -D WIFI_PASSWORD=\"YOUR_WIFI_PASSWORD\"
    -D MDNS_HOSTNAME=\"rhodoshield"

