; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:rhodoshield]
platform = espressif32
board = esp32dev
board_upload.flash_size = 4MB
framework = espidf
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, direct

[env:calibration] ; pio run -e calibration -t upload
platform = espressif32
board = esp32dev
board_upload.flash_size = 4MB
framework = espidf
monitor_speed = 115200
build_flags = -D RUN_CALIBRATION_MODE=1
monitor_filters = esp32_exception_decoder, direct

