; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
extra_configs = config.ini

[env:rhodoshield]
platform = espressif32
board = esp32dev
framework = espidf
board_upload.flash_size = 4MB
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, direct
build_flags = 
    ${network.build_flags}
    ${moisture.build_flags}
    ${gpio.build_flags}
    ${agriculture.build_flags}
    ${time.build_flags}

[env:calibration]
platform = espressif32
board = esp32dev
framework = espidf
board_upload.flash_size = 4MB
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, direct
build_flags = 
    ${network.build_flags}
    ${moisture.build_flags}
    ${gpio.build_flags}
    ${agriculture.build_flags}
    ${time.build_flags}
    -D RUN_CALIBRATION_MODE=1